sudo: true
language: python
matrix:
  include:
    - python: '3.6'
      env: DEPLOY_DOCKER_IMAGE=true
services:
  - docker
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - flake8 app tests
  - make travis-build
after_success:
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # travis encrypt "DOCKER_USERNAME=... DOCKER_PASSWORD=..."
    - secure: "trol95+8Hu/XrTWwmlxjhuo6mdv3JsFwWYL1oJJWmXT8niQnV5CNMuOGH3E38bxBV5t4NakvMgLlQZDP91upBLZ2xcuTq6y52NSDgcD9PoR7CRVDtW3AtenQRH2GzMQS3we3gE8mGAnPmOqDLvIMzhfwE9rvKELiL0Wy/XOZ5MMtsNCk6EHb8n7X+I0vc9Pwk/2VR8Dids+Pe6zZt3EBLiTpkosIcnANlJpHtN8PtPyuO7ZsNg9f6Hi0EvhrUkznQGGVW3VXOCyi4NUylOQcr0d6xMD27+CIa/7pUVsLTjqC4iBctEsGtsr4RJEegJ4VD5ILgkEIRhbcwKIVnz5tVH0otlz/S5qxIVHHj3N8zaNiyF8AOQ0GdC5I88wNf7OrB/RENS1G+wjv9Kb9FSjYX/O39MfSfDi26Qnxc9wjzkhnwRW7HkI01e07igUGSRbixSd/LjikqdEcwr9xUw7QEhve7sRelmczMdasMlxcLdw/U2tc0BzppSw0UpvLFeJGy7b65wSsEhwXZSQ57YYBTJWPLkyp9wdWHtgvQuCMFWsUMLIB3B38pNulltJgPZkSns9LSQmuBkuhjMjSvrhd0efoYEuWBdw39OjEoE5P9TIttY4vTxzePM6UQbXmGXlQ/SDs+Drlj2kbLidljKsDSRBI/sIf9PKH3/7lzxXPjkk="
