kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: squash-bokeh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: squash-bokeh
        track: stable
    spec:
      containers:
        - name: nginx
          image: nginx:1.13-alpine
          lifecycle:
            preStop:
              exec:
                command: ['/usr/sbin/nginx','-s','quit']
          volumeMounts:
            - name: nginx-conf
              mountPath: '/etc/nginx/conf.d'
            - name: tls-certs
              mountPath: '/etc/tls'
        - name: bokeh
          image: lsstsqre/squash-bokeh:{{ TAG }}
          ports:
            - name: http
              containerPort: 5006
          env:
            - name: SQUASH_BOKEH_SERVICE_HOST
              value: {{ HOST }}
            - name: SQUASH_BOKEH_SERVICE_PORT
              value: {{ PORT }}
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs
        - name: nginx-conf
          configMap:
            name: squash-bokeh-nginx-conf
            items:
              - key: 'nginx.conf'
                path: 'nginx.conf'

